version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DEVZ_SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=development
    command: python main.py
