version: '3.8'

services:
  web:
    build: .
    ports:
      - "${DOCKER_PORT}:${DOCKER_PORT}"
    volumes:
      - .:/app
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DEVZ_SECRET_KEY=${DEVZ_SECRET_KEY}
      - DOCKER_PORT=${DOCKER_PORT}
      - FLASK_ENV=development
    command: python main.py
